// <auto-generated />
namespace APP_WEB_MVC_LOCALDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addingclientvalues : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingclientvalues));
        
        string IMigrationMetadata.Id
        {
            get { return "201709201544173_adding-client-values"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
